"""initial_schema

Revision ID: cae0ae9ef1c7
Revises: 
Create Date: 2026-08-23 01:03:30.758998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae0ae9ef1c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('dubbing', 'subtitles', 'transcription', name='servicetype'), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'youtube', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('input_video_path', sa.String(), nullable=False),
    sa.Column('output_dir', sa.String(), nullable=False),
    sa.Column('output_mode', sa.Enum('subtitles_only', 'burn_subtitles', 'soft_subtitles', 'dubbed', name='outputmodevalue'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'downloading', 'running', 'completed', 'failed', name='projectstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
